apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: glowcart
  labels:
    app.kubernetes.io/name: glowcart-backend
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: glowcart-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: glowcart-backend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http