apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: glowcart
  labels:
    app.kubernetes.io/name: glowcart-frontend
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: glowcart-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: glowcart-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http